services:
  # FastAPI Backend Service
  - type: web
    name: nasa-backend
    runtime: python
    buildCommand: "cd 'NASA Backend' && pip install -r requirements.txt"
    startCommand: "cd 'NASA Backend' && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /opt/render/project/src/NASA Backend
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USER
        sync: false
      - key: NEO4J_PASSWORD
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production

  # React Frontend Service
  - type: web
    name: nasa-frontend
    runtime: node
    buildCommand: "cd 'NASA Frontend' && npm ci && npm run build"
    staticPublishPath: "./NASA Frontend/dist"
    plan: free
    headers:
      - path: /*
        name: X-Robots-Tag
        value: noindex
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        fromService:
          name: nasa-backend
          type: web
          property: host

databases: []